(include_subdirs unqualified)

(melange.emit
 (target output)
 (alias react)
 (libraries reason-react lib)
 (modules :standard \ main)
 (preprocess
  (pps melange.ppx reason-react-ppx))
 (module_systems es6))

(melange.emit
 (target node)
 (alias node)
 (libraries lib reason-react)
 (modules main)
 (module_systems
  (es6 mjs)))
